# Generated by Django 3.0.6 on 2020-12-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilereviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='rcount',
            field=models.IntegerField(default=1),
        ),
    ]
