# Generated by Django 3.0.6 on 2020-12-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilereviews', '0002_auto_20201211_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
